import logging
from typing import List, Dict, Any
import numpy as np

from strategies.strategy_factory import SingleInputStrategyFactory


class ARCSolverOrchestrator:
    """
    Orchestrates ARC grid transformation synthesis using a named strategy.
    
    Strategy is selected by name and loaded via StrategyFactory.
    """

    def __init__(self, strategy_name: str, analyzer=None, synthesizer=None, logger: logging.Logger = None):
        self.strategy_name = strategy_name
        self.analyzer = analyzer
        self.synthesizer = synthesizer
        self.logger = logger or logging.getLogger(__name__)
        self.strategy = self._load_strategy()

    def _load_strategy(self):
        """Load strategy class from name using factory"""
        try:
            return SingleInputStrategyFactory.create_strategy(
                self.strategy_name,
                analyzer=self.analyzer,
                synthesizer=self.synthesizer,
                logger=self.logger
            )
        except ValueError as e:
            self.logger.error(f"Failed to load strategy '{self.strategy_name}': {str(e)}")
            raise

    def solve(self, input_grid: List[List[int]], output_grid: List[List[int]]) -> Dict[str, Any]:
        """
        Main solving interface.
        
        Args:
            input_grid: Input grid as 2D list
            output_grid: Target output grid as 2D list
            
        Returns:
            Dictionary containing:
                - 'solution': Best program found
                - 'confidence': Score between 0.0 and 1.0
                - 'success': Whether perfect match was found
                - 'alternatives': Other valid programs
        """
        # Convert to NumPy
        input_np = np.array(input_grid)
        output_np = np.array(output_grid)

        # Run strategy
        raw_results = self.strategy.synthesize(input_np, output_np)

        if not raw_results:
            raise RuntimeError("No valid solutions generated by strategy")

        # Return best result + alternatives
        best_result = raw_results[0]
        return best_result